# Generated by Django 4.2.1 on 2023-05-11 00:41

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etc_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbacktimerange',
            options={'ordering': ['day_of_week', 'start'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
        migrations.AddField(
            model_name='playbacksettings',
            name='default_playlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etc_player.playlist'),
        ),
        migrations.AlterField(
            model_name='playbacktimerange',
            name='end',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='playbacktimerange',
            name='start',
            field=models.TimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='ManualOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Play'), (1, 'Stop')])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etc_player.playlist')),
            ],
            options={
                'verbose_name': 'Manual Override',
                'verbose_name_plural': 'Manual Overrides',
                'ordering': ['-timestamp'],
            },
        ),
    ]
